# Generated by Django 4.0.2 on 2022-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_alter_vaga_data_hora_entrevista_alter_vaga_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.CharField(choices=[('C', 'Candidatado'), ('W', 'Aguardando retorno'), ('S', 'Entrevista agendada'), ('R', 'Rejeitado')], default='C', error_messages={'blank': 'O campo Situação é obrigatório.', 'invalid_choice': 'O campo Situação contém um valor inválido.'}, max_length=1),
        ),
    ]
