# Generated by Django 4.0.2 on 2022-02-11 19:38

from django.db import migrations, models
import vagas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=100)),
                ('empresa_endereco', models.CharField(max_length=200)),
                ('empresa_email', models.EmailField(max_length=254)),
                ('empresa_site', models.URLField()),
                ('empresa_telefone_celular', models.CharField(max_length=11)),
                ('empresa_telefone_comercial', models.CharField(max_length=10)),
                ('cargo_titulo', models.CharField(max_length=50)),
                ('cargo_descricao', models.TextField()),
                ('site_referencia', models.URLField()),
                ('data_hora_entrevista', vagas.models.DataHoraField()),
            ],
        ),
    ]
