# Generated by Django 4.0.2 on 2022-02-13 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_vaga_empresa_telefone_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_hora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
