# Generated by Django 4.0.2 on 2022-02-25 00:40

import django.core.validators
from django.db import migrations, models
import vagas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_alter_vaga_empresa_email_alter_vaga_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='cargo_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='cargo_titulo',
            field=models.CharField(error_messages={'blank': 'O campo Título do cargo é obrigatório.', 'max_length': 'O campo Título do cargo pode conter no máximo %(limit_value)s caracteres.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_hora_entrevista',
            field=models.DateTimeField(blank=True, error_messages={'invalid_datetime': 'O campo Data e hora da entrevista deve conter uma data e horário válidos. Ex.: dd/mm/YYYY HH:ii'}, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='empresa_telefone_comercial',
            field=vagas.models.TelefoneField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='O campo Telefone comercial da empresa deve conter um número válido. Ex.: (DDD) 9999-9999', regex='^\\(\\d{2}\\) \\d{4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='site_referencia',
            field=models.URLField(error_messages={'blank': 'O campo Site de referência é obrigatório.', 'invalid': 'O campo Site de referência deve conter um endereço web válido.'}),
        ),
    ]
