# Generated by Django 4.0.2 on 2022-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_alter_vaga_cargo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='situacao',
            field=models.CharField(blank=True, choices=[('W', 'Aguardando retorno'), ('S', 'Entrevista agendada'), ('R', 'Rejeitado')], default='W', max_length=1),
        ),
    ]
