# Generated by Django 4.0.2 on 2022-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_alter_vaga_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_hora_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.CharField(choices=[('W', 'Aguardando retorno'), ('S', 'Entrevista agendada'), ('R', 'Rejeitado')], default='W', error_messages={'blank': 'O campo Situação é obrigatório.', 'invalid_choice': 'O campo Situação contém um valor inválido.'}, max_length=1),
        ),
    ]
